# Change these first
owner: joshghent # Your GitHub organization or username, where this repository lives
repo: loginllama-status # The name of this repository

sites:
  - name: Loginllama
    url: https://loginllama.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.loginllama.app
  # baseUrl: /loginllama-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Loginllama Status
  introTitle: "**LoginLlama** is a suspicious login detection platform built for developers and security engineers in a hurry. Integrate in 10 minutes"
  introMessage: This is the status page of LoginLlama. If you spot something wrong with our systems please contact us via [Twitter](https://x.com/loginllamaapp)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
